databaseUrl {
  dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
  properties = {
    driver = "org.postgresql.Driver"
    url = "postgres://u2gs3teph4c6r1:p62927feff907726727bb3e864fd1fc592ba5ee51b809106ef0c0097e59b00c1f@cbec45869p4jbu.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d7b32tv8s2pjet"
  }
}